version: "3.9"
services:
  prometheus:
    image: bitnami/prometheus
    volumes:
      - ../prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    container_name: prometheus-container
    network_mode: host 

  inventory_server:
    build: ../inventory_server
    container_name: inventory_server-container
    network_mode: host 

  custom_service_discovery:
    build: ../prometheus_python_client
    container_name: custom_service_discovery
    network_mode: host 
